# Generated by Django 5.2.3 on 2025-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
            ],
        ),
    ]
